task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 10 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  total_batch_size: 32
  dataset:
    type: CocoDetection
    img_folder: ./dataset/driveu/images/train
    ann_file: ./dataset/driveu/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  total_batch_size: 32
  dataset:
    type: CocoDetection
    img_folder: ./dataset/driveu/images/val
    ann_file: ./dataset/driveu/annotations/instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
