__include__: [
  './dfine_hgnetv2_x_coco.yml',
  '../dataset/driveu_detection.yml',
  '../base/deim.yml',
  "../base/dinov2.yml",
]

output_dir: ./outputs/deim_dinov2_s_driveu
  
optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000005   
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.000125
  
DINOv2:
  name: "S"
  return_idx: [-3, -2, -1]
  freeze_stem_only: True
  freeze_at: 12
  # freeze_at: 0
  freeze_norm: True
  # freeze_at: -1         # 0 default
  # freeze_norm: False    # True default
# Increase to search for the optimal ema
epoches: 174 # 72 + 2n  # Adjusted for DriveU dataset size(41k) vs COCO (118k)

## Our LR-Scheduler
flat_epoch: 87    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2  # Adjusted for DriveU dataset size(41k) vs COCO (118k)
no_aug_epoch: 24  # Adjusted for DriveU dataset size(41k) vs COCO (118k)

train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [12, 87, 150]   # list   # Adjusted for DriveU dataset size(41k) vs COCO (118k)

  collate_fn:
    mixup_epochs: [12, 87]  # Adjusted for DriveU dataset size(41k) vs COCO (118k)
    stop_epoch: 150  # Adjusted for DriveU dataset size(41k) vs COCO (118k)