__include__: [
  './dfine_hgnetv2_x_coco.yml',
  '../dataset/driveu_detection.yml',
  '../base/deim.yml',
]

output_dir: ./outputs/deim_hgnetv2_x_driveu
  
optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00000125  # Adjusted for smaller batch size
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.000125  # Adjusted for smaller batch size
  betas: [0.9, 0.999]
  weight_decay: 0.000125

val_dataloader:
  total_batch_size: 8

# Increase to search for the optimal ema
epoches: 174 # 72 + 2n  # Adjusted for DriveU dataset size(41k) vs COCO (118k)

## Our LR-Scheduler
flat_epoch: 87    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2  # Adjusted for DriveU dataset size(41k) vs COCO (118k)
no_aug_epoch: 24  # Adjusted for DriveU dataset size(41k) vs COCO (118k)

train_dataloader: 
  total_batch_size: 8
  dataset: 
    transforms:
      policy:
        epoch: [12, 87, 150]   # list   # Adjusted for DriveU dataset size(41k) vs COCO (118k)

  collate_fn:
    mixup_epochs: [12, 87]  # Adjusted for DriveU dataset size(41k) vs COCO (118k)
    stop_epoch: 150  # Adjusted for DriveU dataset size(41k) vs COCO (118k)